### PR TITLE
Used crontab for refreshing page every 10 minutes

### PR DESCRIPTION
**Pull request by savish28**

### CODE REVIEW

**Review by Sing-Li — COMMENTED** [review]
@savish28   
1)  you actually did not have to create a second PR, you could have edited the title of your first one
2)  this is not a good solution, imagine 15 students/mentor looking at the leaderboard and start clicking refresh... what happens?  And how does that interact with your cron job also clicking refresh  ;  please consider how you can "lock and share" this long-running resource (refresh task)

**Comment by kb0304** [comment]
@savish28 We want to remove a user's ability to refresh, the whole thing would just be done via a cron job.

**Comment by Sing-Li** [comment]
What @kb0304  said is ideal.   The leaderboard then just automatically update every x minutes.d

Easier to install, and no maintenance needed.

@savish28 please also:

1)  remove **_refresh_** altogether from the UI
2)  modify `README.md` to remove any mention of **_refresh_**

Thanks.

**Comment by savish28** [comment]
@kb0304 @Sing-Li  I have removed the user ability to refresh and the job is done by cron jobs. I am now working on changing the flow of our refresh. Do we require to fetch the repo list corresponding to the Gsoc org everytime cronjob is executed or we should fetch them during server setup and just refresh the contributions by cron jobs?

**Comment by kb0304** [comment]
@savish28 Fetch them everytime. Thanks.

**Pull request merged**
